#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
npm run-script format

npm run-script build

git add ./dist/*

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0